### ISSUE TITLE
MVP: User auth

### ISSUE THREAD

**Issue by jbirondo** [jbirondo/Fullstack#3]
[] Users can login/sign up and log out via modal
[] Show errors on login/sign up
[] Users bootstrapped
[] Drop down logout button

**Comment by wongshington** [comment]
- [ ] sign up form needs first name and last name fields
- [ ] "Welcome to OpenTable!"/"Please Sign In" should be bigger on the form
- [ ] the links on the bottom that go to the other form should be styled to show that they're links
- [ ] demo user
